spring:
  application:
    name: cds
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/test

server:
  port: 9000

cds:
  default_min_salary: 4000.0
  upload:
    success_url: /users
    failure_url: /users
