spring:
  application:
    name: cds
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost/test

server:
  port: 8080

logging:
  level:
    root: INFO
    com.opencsv: ERROR
    org.apache: ERROR
    org.hibernate: ERROR
    org.springframework: ERROR
    sg.gov.tech: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: cds.log

springdoc:
  api-docs:
    path: /api-docs

cds:
  default_min_salary: 4000.0
  upload:
    success_url: /users
    failure_url: /error
